### ISSUE TITLE
>the map the death occurred on is not tracked.

### ISSUE THREAD

**Issue by Jordie0608** [nfreader/newSS13tools#12]
https://github.com/nfreader/newSS13tools/blob/master/stats/deaths.php#L8
https://github.com/tgstation/tgstation/blob/master/SQL/tgstation_schema.sql#L138

Get with the times nerd.

**Comment by Jordie0608** [comment]
It turns out Lzi's SQL was borked per https://github.com/tgstation/tgstation/pull/23656 so he's the real nerd here.

**Comment by nfreader** [comment]
Oh this has been fixed for a long time.
