### ISSUE TITLE
Brace for tgstation/tgstation/24345

### ISSUE THREAD

**Issue by nfreader** [nfreader/newSS13tools#19]
At worst, tgstation/tgstation#24345 will break server IP mapping since it's splitting it by port and IP.

**Comment by MrStonedOne** [comment]
did you not notice, it also changes all ip fields to be numbers, and you have to use inet_itoa to get an ip in dotted form (or the php version of the same thing)

**Comment by nfreader** [comment]
I just split the IP on the `:` to get the port # and differentiate the servers based on your recommendation. Is there a better way to do that?

**Comment by Jordie0608** [comment]
The IP will be an unsigned int and requires the use of `INET_NOTA()` to get the proper form
See: http://stackoverflow.com/questions/2542011/most-efficient-way-to-store-ip-address-in-mysql

**Comment by Jordie0608** [comment]
Apparently it's `long2ip()` in PHP http://php.net/long2ip

**Comment by MrStonedOne** [comment]
ie: 127.0.0.1 would be stored 2130706433

This is for all ip fields, including the connection log and the player table.

**Comment by nfreader** [comment]
Huh. Learn something new every day.

**Comment by nfreader** [comment]
Well nothing exploded.
