### ISSUE TITLE
Rounds index inconsistent links

### ISSUE THREAD

**Issue by Jordie0608** [nfreader/newSS13tools#20]
On the rounds list page only the first table cell is a href, as such only the round ID can i.e. be used with middle or right click to open in new tab. The rest of the cells work for left click.

This is at best only slightly annoying.

**Comment by nfreader** [comment]
That's what I get for trying to make the entire row clickable. I'll look into a better way to implement this.

**Comment by nfreader** [comment]
Aaaaand fixed, many commits ago
