### ISSUE TITLE
Ban duration is irrelevant

### ISSUE THREAD

**Issue by nfreader** [nfreader/newSS13tools#22]
Use expire time instead and calculate duration in the query.

**Comment by Jordie0608** [comment]
One of those things we've just never got around to doing; this isn't really a problem with your tools however?

**Comment by nfreader** [comment]
Yea, I'm using it directly.

**Comment by Jordie0608** [comment]
I mean the duration column existing at all is a codebase problem, see #6174 (idk why it was closed), not one for your site. Unless you're referring to doing what is mentioned in that issue locally?

**Comment by optimumtact** [comment]
I closed a tonne of not a bug issues because I'm a hardass and they can go in the forum.

and by a tonne I mean all of them

**Comment by nfreader** [comment]
Whoops, this has been resolved for some time.
