### ISSUE TITLE
Library DB Editor

### ISSUE THREAD

**Issue by peoplearestrange** [nfreader/newSS13tools#26]
Is there a way that admins can edit the book library data?

It be great if we could edit the categories for example. Or just plain delete 1 word "test" books and the like.

**Comment by nfreader** [comment]
Admins and up can flag books for deletion. I don't have write access to the DB, [so for now I'm just adding a row to another DB/table that I control](https://github.com/nfreader/newSS13tools/blob/master/inc/classes/library.php#L143-L162). At some point, we can go through and use that list to cull the library.

**Comment by peoplearestrange** [comment]
Ah! Ok. Sounds good. A flag for re-categorisation might be useful too. There's a lot of adult stuff that isn't marked as so and other randomly categorised books.
