### ISSUE TITLE
Testmerged PR link broken

### ISSUE THREAD

**Issue by Jordie0608** [nfreader/newSS13tools#55]
Linked has an erroneous `"` `https://github.com/tgstation/tgstation/issues/"2229839`
From https://atlantaned.space/newSS13tools/round.php?round=74956
https://github.com/tgstation/tgstation/issues/%2229839

**Comment by nfreader** [comment]
Yup. I’ve got a big commit in the works that should fix all the weird issues.

**Comment by nfreader** [comment]
Fixed!
