### ISSUE TITLE
Feature request: simple graph showing population

### ISSUE THREAD

**Issue by kingofkosmos** [nfreader/newSS13tools#59]
I might be blind but I couldn't find any info about how many people have connected to the servers during the last few years. Is there a way to see that? When I think about stats about a multiplayer game that info would imho be the main ones which would pop up on the main stats page.

**Comment by nfreader** [comment]
Yeah, I wasn't aware that the information for this was being tracked, but I'm working on this now.

**Comment by nfreader** [comment]
Boom https://atlantaned.space/newSS13tools/stats/serverPop.php

**Comment by kingofkosmos** [comment]
That is freaking awesome! Would it be possible to see further than last month? Excellent job, still.

**Comment by JamieH** [comment]
An additional request - please don't hardcode Sybil/Basil

**Comment by nfreader** [comment]
>An additional request - please don't hardcode Sybil/Basil

I'll fix this at a later date. This is just for the sake of getting some code up.

**Comment by JamieH** [comment]
Yeah it worked for us just says Sybil/Basil, it's cool to see these stats, thanks dude.
