### ISSUE TITLE
Loading round logs before finished taints cache

### ISSUE THREAD

**Issue by JJRcop** [nfreader/newSS13tools#62]
I just tried to load https://atlantaned.space/newSS13tools/round.php?round=76598&logs=true because it was visible on the recent rounds portion of index.php. The round apparently just ended and the logs weren't done parsing yet, so they weren't yet available on the [tgstation13.org website](https://tgstation13.org/parsed-logs/sybil/data/logs). Even so, the logs were "fetched" and cached, even though they weren't available, and they are now cached forever as blank, so you will never see the correct logs on the atlantaned.space website. This can actually be done for any arbitrary round number that doesn't have a file on the remote website, I have done it for [76599](https://atlantaned.space/newSS13tools/round.php?round=76599&logs=true) (which just started right after 76598), and [133337](https://atlantaned.space/newSS13tools/round.php?round=133337&logs=true).

There are potential problems with the tgstation13.org website that could be causing this behavior, if you attempt to visit https://tgstation13.org/parsed-logs/sybil/data/logs/2017/09/25/round-133337 then you will properly be redirercted back to the /25 directory, but adding a forward slash after that, [/round-133337/](https://tgstation13.org/parsed-logs/sybil/data/logs/2017/09/25/round-133337/), gets you thrown in an HTTP 302 loop. Even though this is caused by the tgstation13.org website, newSS13tools should handle this kind of situation on its end.

This situation is unique because there is no HTTP 400 code, just a redirect loop.

It doesn't appear that any sort of sanity checking for expected contents of game.txt or attack.txt is done anywhere.
You could check to make sure that game.txt contains ```GAME: Round ID: ```, and check that the logged round id matches the expected round id, erroring and not saving to cache if it doesn't.

**Comment by nfreader** [comment]
Known issue. Will get fixed when I rewrite log parsing to dump to a DB instead of flatfile. 

Logged-in admins can reset the log cache.

**Comment by nfreader** [comment]
Should be fixed, but most likely created a whole new series of bugs
