### ISSUE TITLE
List admin played internet sounds

### ISSUE THREAD

**Issue by JJRcop** [nfreader/newSS13tools#63]
A few weeks ago I added internet admin sounds in tgstation/tgstation#30457, where an admin can input a web url, which gets played for all players who have it enabled.

The urls that the admins input do get logged, and I think it would be neat to add a new stats page that lists the internet admin sound urls played, along with the round ID.

Here is how they get logged:
https://github.com/tgstation/tgstation/blob/d46477fd163978d0442421c9c5339394610b983b/code/modules/admin/verbs/playsound.dm#L95

If you would like, I can add a blackbox stat called played_urls to make it easier.

**Comment by nfreader** [comment]
If that line isn't caught by MSO's log-censoring pipeline, it's still difficult to extract from the static log files. Adding a database stat would be much, much easier and greatly appreciated.

**Comment by JJRcop** [comment]
Instead of plural played_urls I named it singular played_url since for some reason all the blackbox stats are named that

**Comment by JJRcop** [comment]
@nfreader played_url is now live on both servers, it contains URL entries linking to a user-facing content webpage of some sort. (Basically whatever the admins put in the Play Internet Sound verb) It is only populated when a song successfully plays.

**Comment by nfreader** [comment]
Aaaand done
